service: myserverlessproject

provider:
    name: aws
    runtime: nodejs12.x
    profile: serverlessUser
    environment:
        tableName: ${self:custom.tableName}

custom:
    tableName: my-players-table

functions:
    getUser:
        handler: lambdas/endpoints/getUser.handler
        events:
            - http:
                  path: get-user/{ID}
                  method: GET
                  cors: true

resources:
    Resources:
        myDynamoTable:
            Type: 'AWS::DynamoDB::Table'
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: ID
                      AttributeType: S
                KeySchema:
                    - AttributeName: ID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
